import pandas as pd 
df = pd.read_csv("Weather.csv")
print(df)
print(df.head())
print(df.tail())
print(df.columns)
print(df.shape)
print(df.info())
print(df.describe())
print(df["City"])
print(df.loc[0])
print(df["Temperature"].mean())
print(df.loc[df["Temperature"].idxmax()])
print(df.loc[df["Temperature"].idxmin()])
print(df[df["Temperature"] > 35])
print(df.sort_values("Rainfall", ascending=False))
print(df.sort_values("Rainfall", ascending=True))